name: Test

on:
  workflow_dispatch:
  
jobs:
  test-unity:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Library
        key: Library
        restore-keys: |
          Library
    - uses: game-ci/unity-test-runner@v4
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: .
        githubToken: ${{ secrets.GITHUB_TOKEN }}
